=== Bokkacheck/ISTrepository/autooglas.dtd
<!ELEMENT AutoOglas (Automobil)+>
<!ELEMENT Automobil (Proizvodjac,Model,Godiste,Farba,Zapremina_motora,Transmisija,Gorivo,Cena,Kontakt)>
<!ELEMENT Proizvodjac (#PCDATA)>
<!ELEMENT Model (#PCDATA)>
<!ELEMENT Godiste (#PCDATA)>
<!ELEMENT Farba (#PCDATA)>
<!ELEMENT Zapremina_motora (#PCDATA)>
<!ELEMENT Transmisija (#PCDATA)>
<!ELEMENT Gorivo (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Kontakt (#PCDATA)>
<!ATTLIST Model tip CDATA #IMPLIED>
<!ATTLIST Farba tip (akril|metalic) #REQUIRED>
<!ATTLIST Transmisija tip (manuelni|auto) #REQUIRED>
<!ATTLIST Gorivo tng (da|ne) #IMPLIED>
<!ATTLIST Zapremina_motora jedinica (ccm|l) #REQUIRED>
<!ATTLIST Cena valuta (din|eur) #REQUIRED>

=== Bokkacheck/ISTrepository/autooglas.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE AutoOglas SYSTEM "autooglas.dtd">

<AutoOglas>
  <Automobil>
    <Proizvodjac>Opel</Proizvodjac>
    <Model tip ="C">Corsa</Model>
    <Godiste>2002</Godiste>
    <Farba tip="metalic">Siva</Farba>
    <Zapremina_motora jedinica="ccm" >1400</Zapremina_motora>
    <Transmisija tip="manuelni">5</Transmisija>
    <Gorivo tng="da">benzin</Gorivo>
    <Cena valuta="eur">1600</Cena>
    <Kontakt>0641231231</Kontakt>
  </Automobil>
  <Automobil>
    <Proizvodjac>Citroen</Proizvodjac>
    <Model tip ="3">C</Model>
    <Godiste>2003</Godiste>
    <Farba tip="metalic">Plava</Farba>
    <Zapremina_motora jedinica="ccm">1400</Zapremina_motora>
    <Transmisija tip="manuelni">5</Transmisija>
    <Gorivo tng="ne">dizel</Gorivo>
    <Cena valuta="eur">1850</Cena>
    <Kontakt>0643213213</Kontakt>
  </Automobil>
</AutoOglas>
